### ISSUE TITLE
cant use the plugin when im using papermc 

### ISSUE THREAD

**Issue by Johnathannj** [amsam0/voicechat-discord#65]
yes i know its for papermc but when i tried to do it it said "NO SIMPLE VOICE CHAT CLIENT" when i cant even download the mod in my server bc the soft ware is for plugins :/

**Comment by amsam0** [comment]
Please provide more context. I have no idea what you are talking about.

The plugin must be installed on the server along with Simple Voice Chat. The client that uses it must not have Simple Voice Chat installed.

**Comment by Johnathannj** [comment]
sorry english is my second lanauga any ways when i decided to make simple voice chat plugin and the simple voice chat discord bridge plugin work i used the command /dvc start and it said it started but the bot left then it said this any way to fix it because i tried a soft ware that adds plugins and mods together but it wasnt starting server
![لقطة شاشة 2024-08-15 112023](https://github.com/user-attachments/assets/5a9cfb91-d495-4081-af90-91656baed7b1)

**Comment by dinushay** [comment]
You can only use this plugin if you have not installed the Simple Voicechat mod. 

This is even said in the error message.

**Comment by amsam0** [comment]
Thank you! Yes, please just read the error message. It says, "Please check that you DO NOT have Simple Voice Chat installed on your client." This means that you must not have Simple Voice Chat installed on your client to use the addon.
