### ISSUE TITLE
Huge Server Thread usage

### ISSUE THREAD

**Issue by DaddyRobLIVE** [amsam0/voicechat-discord#66]
**Describe the bug**
Plugin uses huge server thread

**To Reproduce**
1. Install dvc
2. Wait til you get a lot of players online
3. Do a spark timings

**Expected behavior**
The plugin shouldn't use too much server thread

**Screenshots**
![image](https://github.com/user-attachments/assets/a42286f8-f48f-456f-b888-c20c47c367d6)

**Logs**
First, set `debug_level` to `3` (or `2` if there's too much spam) in the Simple Voice Chat Discord Bridge configuration file. After restarting your server or using `/dvc reloadconfig`, please upload the server logs here (make sure they don't include any sensitive info).

**Versions (please complete the following information):**
- Minecraft: 1.21.2
- Loader (paper, purpur, fabric, quilt, etc): sparklypaper
- Simple Voice Chat: 2.5.20
- Simple Voice Chat Discord Bridge: 3.0.4

**Additional context**
My request is to make the plugin use Async threads instead of the server thread so it doesn't burden it.

**Comment by DaddyRobLIVE** [comment]
Hi, I'm sorry for the lack of context and my request is just my suggestion. I'm not claiming to be an expert. There were 100+ players online. No one's using the voicechat during that time

**Comment by amsam0** [comment]
Sorry, my message came across harshly, you're fine. No one using voicechat? That's weird, the addon shouldn't be doing anything. It'd be great to see the expanded trace.

**Comment by DaddyRobLIVE** [comment]
I'll do more timings and give you enough data for this.

**Comment by amsam0** [comment]
Can you get another timing dump with this nightly build? https://github.com/amsam0/voicechat-discord/actions/runs/10548688425

**Comment by DaddyRobLIVE** [comment]
will test it out when I'm free again.

**Comment by amsam0** [comment]
When you do test, could you set `debug_level` to 3 in the config and send the logs? That would actually be the most helpful. Depending on your host the important logs might not show up though

**Comment by DaddyRobLIVE** [comment]
Sure, I'll do that.

**Comment by amsam0** [comment]
@DaddyRobLIVE Are you still having the issues? If not, let me know so I can close this issue

**Comment by DaddyRobLIVE** [comment]
I'm good, thank you. Looks like it's just your plugin calling the system at times.

**Comment by amsam0** [comment]
3.0.5 should reduce the plugin overhead: https://modrinth.com/plugin/simple-voice-chat-discord-bridge/versions
