### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by zxcycuba** [amsam0/voicechat-discord#67]
Hello, I encountered a problem with voice, everything works perfectly, but when a player from Discord says something, he can’t be heard, the problem is in CoreProtect, I’m sure there are some solutions?

Minecraft: 1.21
Loader (paper, purpur, fabric, quilt, etc):purpur
Simple Voice Chat: 2.5.20
Simple Voice Chat Discord Bridge: 3.0.4

**Comment by amsam0** [comment]
CoreProtect?? I have no idea what that means or how it would cause the addon to stop working. Can you please provide additional details and logs (after setting debug_level to 3 in the config)?

**Comment by zxcycuba** [comment]
CoreProtect this is a plugin for detecting who took/put, broke/installed, in other words, a necessary plugin for SMP Should I send you a screenshot of the logs?

**Comment by zxcycuba** [comment]
I'm going to sleep now because I'm tired, let me send you tomorrow if anything, my time is Moscow time

**Comment by dinushay** [comment]
Hey, I use Paper, but CoreProtect and the VoiceChat bridge plugin works normally for me without issues.

It seems like it's a unique error.

**Comment by zxcycuba** [comment]
I don't know what the problem could be but I'll see tomorrow maybe it conflicts with other plugins what's the joke is that people from Discord can hear conversations of people from mods but when they try to say something their they can't be heard

**Comment by zxcycuba** [comment]
maybe I don't know what plugins you use?

**Comment by zxcycuba** [comment]
there might be a problem GayserMc?

**Comment by dinushay** [comment]
Which plugins I use completely irrelevant, because you said the problem occurs in the context of CoreProtect.

**Comment by zxcycuba** [comment]
sorry

**Comment by dinushay** [comment]
If you are not sure, please check your server logs and share the error message.

**Comment by amsam0** [comment]
@zxcycuba Please read my initial response. If you want any help from me, I need more details

**Comment by zxcycuba** [comment]
hello, sorry for the long answer, everything worked, I replaced debug_level from 0 to 1 and, lo and behold, everything worked, do you by any chance possess forbidden magic?😨

**Comment by zxcycuba** [comment]
and also suggestions) create an application with modification Simple Voice chat for mobile devices

**Comment by amsam0** [comment]
There is a web based addon being developed by another community member but it is not yet publicly available.

**Comment by zxcycuba** [comment]
I noticed interruptions in Discord, what should I do in this case?

**Comment by zxcycuba** [comment]
interruptions

**Comment by amsam0** [comment]
I have no idea what you mean. Please be more descriptive.

**Comment by zxcycuba** [comment]
let's close the topic

**Comment by zxcycuba** [comment]
Do you have plans to add Gui?

**Comment by amsam0** [comment]
No
