### ISSUE TITLE
Install the mod 'OpenJDK 64-Bit Server VM' with version >=21

### ISSUE THREAD

**Issue by PureFuryReal** [amsam0/voicechat-discord#71]
**Describe the bug**
When Loading this mod onto the server simle voice chat and other mods work. However it crashes instantly and give me the message in the photo provided. when I click "solve" there is no mod allowing the "OpenJDK 64-bit Server VM".

**To Reproduce**
1. Go to 'exaroton(Paid) or Aternos(free)'
2. Click on 'create a server(create a server running fabric version 1.20.1 and install simple voice chat and the simple vc discord mod. follow the install steps and run the server)'.
3. Once it crashes 'it should provide with the message(like in the photo.)'
4. you can click "solve" and it brings you to the mod page, however there is no mod that can help with this.

**Expected behavior**
Hopefully a decent walkthrough or possible config/lib mod.

**Screenshots**
![image_2024-10-01_003642541](https://github.com/user-attachments/assets/128d2375-2539-4d23-a356-87ceed425e4c)

**Logs**
First, set `debug_level` to `3` (or `2` if there's too much spam) in the Simple Voice Chat Discord Bridge configuration file. After restarting your server or using `/dvc reloadconfig`, please upload the server logs here (make sure they don't include any sensitive info).

**Versions (please complete the following information):**
- Minecraft: 1.20.1
- Loader (Fabric): 
- Simple Voice Chat: 1.20.1(fabric)
- Simple Voice Chat Discord Bridge: 1.20.1 (fabric)

**Additional context**

**Comment by dinushay** [comment]
Which Java version are you using?

**Comment by amsam0** [comment]
You need to have Java 21 or later. Contact your hosting provider if you don't know how to do that
