### ISSUE TITLE
Can you add this as a feature

### ISSUE THREAD

**Issue by Lets-game6531** [amsam0/voicechat-discord#74]
Hi ai have wondered if you can make it so that there is one bot used and to use it you do the command ‘/dvc start‘ which gives you a code that you dm to the bot and then the bot private calls you,

it would mean that you only need one bot, no one can join the channel when it is in use.

I have no idea if it would be possible, but I thought I should make a suggestion for incase it is possible

**Comment by dinushay** [comment]
I don't think bots can make private calls
