### ISSUE TITLE
I think you need to update the plugin

### ISSUE THREAD

**Issue by Lets-game6531** [amsam0/voicechat-discord#77]
**Describe the bug**
hi when I try to type the '/dvc start' to test out the plugin and it says it does not exist, and when I do the /plugins command  that plugin is red

**Expected behavior**
I expected the command to work so that I can use simple voice chat without the mod

**Screenshots**
![image](https://github.com/user-attachments/assets/2097e25a-41bd-4d8d-9fb7-6d854533f459)

**Logs**
after I type the command in console it says: '[11:43:02 INFO]: Lets_game6531 issued server command: /dvc start'

**Versions (please complete the following information):**
- Minecraft: 1.21
- Loader (paper, purpur, fabric, quilt, etc): paper
- Simple Voice Chat: voicechat-bukkit-2.5.25.jar
- Simple Voice Chat Discord Bridge: voicechat-discord-paper-3.0.5.jar

**Comment by amsam0** [comment]
I need logs to help you. There will be an error message.

**Comment by amsam0** [comment]
Those are not the logs. I mean the full server logs.

**Comment by amsam0** [comment]
Closing in favor of #79
